apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: devadmin-vs
spec:
  hosts:
    - devtest.sreyo.in
  gateways:
    - gateway
  http:
    - route:
        - destination:
            host: admin-service.default.svc.cluster.local
            port:
              number: 1337
