name: "Create Image"

on:
#workflow_dispatch
 pull_request:
   branches:
     - dev
      
jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Push
    runs-on: ubuntu-latest 
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    # Login to Jfrog
    - name: Jfrog login
      env:
        JFROG_USER: ${{ secrets.JFROG_USER }}
        JFROG_PASSWORD: ${{ secrets.JFROG_PASSWORD }}
      run: |
          docker login sreyo.jfrog.io -u $JFROG_USER -p $JFROG_PASSWORD
    
    # Build the Docker image
    - name: Build docker image
      run: |-
        docker build ./backend -t  sreyo.jfrog.io/ddtestadminstrapi-docker-dev-local/adminstrapi-docker
        docker push sreyo.jfrog.io/ddtestadminstrapi-docker-dev-local/adminstrapi-docker 